<div class="instaframe" data-mage-init='{"instaframe":{}}'>
<?php
    $data = $block->getFeedData();
    // \Zend_Debug::dump($data);die;
    foreach ($data as $option):
?>
    <div class="instaframe-item">
        <div class="instaframe-front">
            <div class="instaframe-likes">
                <a  href="<?php echo $option['link'] ?>" class="instaframe-url">
                    <?php echo $option['likes'] ?>
                </a>
            </div>
            <div class="instaframe-comments">
                <a  href="<?php echo $option['link'] ?>" class="instaframe-url">
                    <?php echo $option['comments'] ?>
                </a>
            </div>
            <div class="instaframe-image">
                    <?php if ($option['type'] == 'video' || $option['video_first'] ): ?>
                        <video  width="<?php echo $option['images']['width'] ?>px"
                                height="<?php echo $option['images']['height'] ?>px"
                                controls>
                            <source     src="<?php echo $option['images']['url'] ?>"
                                        type="video/mp4">
                            Your browser does not support the video tag.
                        </video>
                    <?php else: ?>
                        <img    src="<?php echo $option['images']['url'] ?>"
                                alt="<?php echo $option['caption'] ?>"
                                height = "<?php echo $option['images']['height'] ?>px"
                                width = "<?php echo $option['images']['width'] ?>px"
                                class="instaframe-image"  >
                    <?php endif; ?>
                </a>
            </div>
        </div>
        <div class="instaframe-back">
            <div class="instaframe-caption">
                <?php echo $option['caption'] ?>
            </div>
        </div>
    </div>
<?php
    endforeach;
?>
</div>
